apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: filebot-parser
  namespace: lavanda
spec:
  schedule: "@hourly"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: filebot-parser
              image: lavandadelpatio/filebot-parser
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_DATA_MONGODB_URI
                  valueFrom:
                    secretKeyRef:
                     name: mongodb-uri
                     key: secret
                - name: SPRING_PROFILES_ACTIVE
                  value: pro     
                - name: FILEBOT_PATH
                  value: /data/.reports
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
              volumeMounts:
                - mountPath: /data
                  name: filebot-config
          restartPolicy: Never
          volumes:
            - name: filebot-config
              persistentVolumeClaim:
                claimName: filebot-config
