apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: filebot
  namespace: lavanda
spec:
  schedule: "@hourly"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: filebot
              image: rednoah/filebot
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
              # command: ["/bin/sleep", "3650d"]
              command:
                - /bin/sh
                - -c
                - filebot -no-xattr -script 'fn:amc' /media/Descargas --output /media --action move -non-strict --order Airdate --conflict skip -no-xattr --lang es --def 'music=y' 'unsorted=y' 'storeReport=/data/.reports' 'seriesFormat=/media/Series/{n}/ Season {s}/{n} s{s.pad(2)}e{e.pad(2)}' 'movieFormat=/media/Peliculas/{n} ({y})' 'unsortedFormat=/media/Downloaded/Unsorted/{fn}.{ext}' 'excludeList=/data/.excludes'; (([ $? -eq 100 ] || [ $? -eq 0 ]))
              volumeMounts:
                - mountPath: /media
                  name: filebot-media
                - mountPath: /data
                  name: filebot-config
          restartPolicy: OnFailure
          nodeSelector:
            cputype: amd64
          volumes:
            - name: filebot-media
              nfs:
                server: 10.10.120.50
                path: /media/Externo8TB_2
            - name: filebot-config
              persistentVolumeClaim:
                claimName: filebot-config-rwm
