apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: filebot-parser
  namespace: lavanda
spec:
  schedule: "@hourly"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: filebot-parser
              image: lavandadelpatio/filebot-parser:0.0.5
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_DATA_MONGODB_URI
                  valueFrom:
                    secretKeyRef:
                     name: mongodb-uri
                     key: secret
                - name: SPRING_PROFILES_ACTIVE
                  value: pro     
                - name: FILEBOT_PATH
                  value: /data/.reports
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: aws-access-key-id                
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: aws-access-secret-key   
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
              volumeMounts:
                - mountPath: /data
                  name: filebot-config
          restartPolicy: OnFailure
          nodeSelector:
            cputype: amd64
          volumes:
            - name: filebot-config
              persistentVolumeClaim:
                claimName: filebot-config-rwm
