suspend" : true 
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: filebot-maintenance
  namespace: lavanda
spec:
  schedule: "@hourly"
  suspend: true
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: filebot-maintenance
              image: rednoah/filebot
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
              command: ["/bin/sleep", "3650d"]
              volumeMounts:
                - mountPath: /media
                  name: filebot-media
                - mountPath: /data
                  name: filebot-config
          restartPolicy: Never
          volumes:
            - name: filebot-media
              nfs:
                server: 10.10.120.50
                path: /media/Externo8TB_2
            - name: filebot-config
              persistentVolumeClaim:
                claimName: filebot-config
