apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: feed-films
  namespace: lavanda
spec:
  schedule: "@hourly"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: feed-films
              image: lavandadelpatio/feed-films:0.0.2
              imagePullPolicy: IfNotPresent
              env:
                - name: SPRING_RABBITMQ_USERNAME
                  value: user
                - name: SPRING_RABBITMQ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: rabbitmq
                      key: rabbitmq-password 
                - name: SPRING_RABBITMQ_HOST
                  value: rabbitmq  
          restartPolicy: Never
          nodeSelector:
            cputype: arm64
