apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-uri
  namespace: lavanda
spec:
  encryptedData:
    secret: AgArXvSokpx3Pr6AiKS/cMAH8ABnQwTjh0q+uva9rztkmeIJTX+c0UaoWxYZA0t6AeLd2hThPvW91FKEJ/th56mwrf5wJ6rrmuHVKgs61xv235fIYgVm1oGqCxZtOj7UZMc0bXlaQUjy50wkvJf1sC2ni+vG9GpWVXM4NZJ0iIwlJ1dP4o0P20Cn17dmzF/UrlgDAbyXjt/rkU3vZh6rySvw/pK9ZA7BykSC+8HEA8cqOF62ALadT5s9uKsI2YMDKi1JFoRwfBn/c38W5yEjSH1p1LIbhhl23EVqw+ijvQRNBKryts5ekk4RbFrbBmtuYTwmwVWLxvQlcVm/o9crdmApX9MT46U+njfl6qpUp7g8u769hPkm2u7zJTCjTFje6SBfnanDNBMht4ngD99wsDgwyM7CFbqmdbJ5E0V+oEzZw96PKl9F+wvyfpfBnBOugi/TDKIDcqBvHSL1oKZxQab8P4IDJ9SAKebPug+zt10SoOJ+osxVu93cvuT1QTTO325q54YgB565nZskmUpHXKggHo8XU6Hwg+JH6lwG7pjDgDSyehCkRTxZzaOJNYFIty226P4L3J3hJpP0K4jJk6TgWsT7DTzVo9FtGFdYzK6sj7gtSK+ztkfYiinePdHLVDh8T5OsGf9MFwUUutYjB26Wt7FloqfiwGstmP1vB1C+pdJLC53cicVqUIukg2M7quMXbRnvBmYEcJCwyjOd0TefFfoE9xL99N/oXYyk6NU5asGPpVER3KSjHqGu0xjdgSN6WO0agd/wngHJHzKukhzNUzg7zic356ZqcY3G1p5ZgIiDBbFwkeELY8M31My7/YACP+yKMQkBfbFNAA==
  template:
    metadata:
      name: mongodb-uri
      namespace: lavanda
