apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "plex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plex.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plex.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 32400
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: plex-config-volume
            # - mountPath: /data
              # name: plex-empty-dir  
            - mountPath: /media/4TB_1/Peliculas
              name: plex-media-films1volume  
            - mountPath: /media/4TB_2/Peliculas
              name: plex-media-films2volume  
            - mountPath: /media/4TB_3/Peliculas
              name: plex-media-films3volume 
            - mountPath: /media/4TB_4/Peliculas
              name: plex-media-films4volume
            - mountPath: /media/Externo8TB_1/Peliculas
              name: plex-media-films5volume  
            - mountPath: /media/Externo8TB_2/Peliculas
              name: plex-media-films6volume   
            - mountPath: /media/4TB_1/Series
              name: plex-media-shows1volume  
            - mountPath: /media/4TB_2/Series
              name: plex-media-shows2volume  
            - mountPath: /media/4TB_3/Series
              name: plex-media-shows3volume 
            - mountPath: /media/4TB_4/Series
              name: plex-media-shows4volume
            - mountPath: /media/Externo8TB_1/Series
              name: plex-media-shows5volume  
            - mountPath: /media/Externo8TB_2/Series
              name: plex-media-shows6volume               
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: VERSION
              value: "docker"      
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: plex-config-volume
          persistentVolumeClaim:
            claimName: plex-config
        - name: plex-media-films1volume
          glusterfs:
            endpoints: glusterfs-cluster
            path: gluster-films1
            readOnly: false
        - name: plex-media-films2volume
          glusterfs:
            endpoints: glusterfs-cluster
            path: gluster-films2
            readOnly: false
        - name: plex-media-films3volume
          glusterfs:
            endpoints: glusterfs-cluster
            path: gluster-films3
            readOnly: false
        - name: plex-media-films4volume
          glusterfs:
            endpoints: glusterfs-cluster
            path: gluster-films4
            readOnly: false
        - name: plex-media-films5volume
          glusterfs:
            endpoints: glusterfs-cluster
            path: gluster-films5
            readOnly: false
        - name: plex-media-films6volume
          glusterfs:
            endpoints: glusterfs-cluster
            path: gluster-films6
            readOnly: false
        - name: plex-media-shows1volume
          glusterfs:
            endpoints: glusterfs-cluster
            path: gluster-shows1
            readOnly: false
        - name: plex-media-shows2volume
          glusterfs:
            endpoints: glusterfs-cluster
            path: gluster-shows2
            readOnly: false
        - name: plex-media-shows3volume
          glusterfs:
            endpoints: glusterfs-cluster
            path: gluster-shows3
            readOnly: false
        - name: plex-media-shows4volume
          glusterfs:
            endpoints: glusterfs-cluster
            path: gluster-shows4
            readOnly: false
        - name: plex-media-shows5volume
          glusterfs:
            endpoints: glusterfs-cluster
            path: gluster-shows5
            readOnly: false
        - name: plex-media-shows6volume
          glusterfs:
            endpoints: glusterfs-cluster
            path: gluster-shows6
            readOnly: false    
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
