apiVersion: v1
kind: Service
metadata:
  name: elastictranscoder-test-media-storage-headless
  labels:
    app: elastictranscoder-test-media-storage
spec:
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: elastictranscoder-test-media-storage
