apiVersion: v1
kind: Service
metadata:
  name: elastictranscoder-media-storage-test-no-headless
  namespace: elastictranscoder-test
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: elastictranscoder-test-media-storage
  type: ClusterIP
