apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-deployment
  namespace: lavanda
spec:
  selector:
    matchLabels:
      app: ubuntu
  replicas: 1
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          command: ["sleep", "123456"]
          volumeMounts:
           - mountPath: /data
             name: filebot-config     
      nodeSelector:
        cputype: amd64
      volumes:
        - name: filebot-config
          persistentVolumeClaim:
            claimName: filebot-config-rwm      
