apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudwatch-adapter.fullname" . }}
  labels:
    {{- include "cloudwatch-adapter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
  selector:
    {{- include "cloudwatch-adapter.selectorLabels" . | nindent 4 }}
