global:
  aws:
    accessKeyId: 
    secretAccessKey: 
  okta:
    issuer: 
    clientId: 
    clientSecret:  
media:
  image:
    tag: "2c577713"  
media-storage:
  image:
    tag: "2c577713"  
transcoder:
  image:
    tag: "c596216b"             
transcoder-handler:
  image:
    tag: "2c577713"  